const knex = require('knex');

/**
 * DatabaseService handles direct interaction with the database via Knex.js.
 */
class DatabaseService {
    /**
     * Creates a Knex connection dynamically from a connection string.
     * @param {string} connectionString - ej: postgresql://user:pass@localhost:5432/db
     * @returns {import('knex').Knex}
     */
    _createConnection(connectionString) {
        const url = new URL(connectionString);
        const protocol = url.protocol.replace(':', '');
        // Map common URL protocols to Knex client names
        const clientMap = {
            'postgresql': 'pg',
            'postgres': 'pg',
            'pgsql': 'pg',
            'mysql': 'mysql2',
            'mariadb': 'mysql2',
            'sqlserver': 'mssql',
            'mssql': 'mssql',
            'oracle': 'oracledb',
            'sqlite': 'sqlite3'
        };
        const client = clientMap[protocol] || 'pg';
        return knex({
            client: client,
            connection: {
                host: url.hostname,
                port: parseInt(url.port, 10) || 5432,
                user: decodeURIComponent(url.username),
                password: decodeURIComponent(url.password),
                database: url.pathname.replace('/', '')
            },
            pool: { min: 0, max: 1 }
        });
    }

    /**
     * Retrieves database schema using INFORMATION_SCHEMA.
     * @param {string} sql - SQL query to execute against information_schema
     * @param {string} connectionString - Dynamic database connection string
     * @returns {Promise<Array>}
     */
    async getSchema(sql, connectionString) {
        let db;
        try {
            db = this._createConnection(connectionString);
            const result = await db.raw(sql);
            return result.rows || result[0];
        } finally {
            if (db) await db.destroy();
        }
    }

    /**
     * Executes a SELECT query against the database with a security LIMIT 100.
     * @param {string} sql - Final SQL query generated by the AI agents
     * @param {string} connectionString - Dynamic database connection string
     * @returns {Promise<Array>}
     */
    async executeQuery(sql, connectionString) {
        let db;
        try {
            db = this._createConnection(connectionString);
            const result = await db.raw(sql);
            return result.rows || result[0];
        } finally {
            if (db) await db.destroy();
        }
    }

    /**
     * Anonymizes schema columns based on PII analysis instructions.
     * For now applies a basic anonymization of suspicious column names.
     * @param {Array} schema - Schema data from INFORMATION_SCHEMA
     * @param {Object} instructions - PII detection results from Compliance Analyst
     * @returns {Promise<Array>}
     */
    async anonymizeSchema(schema, instructions) {
        const isPii = (colName) => {
            const piiKeywords = ['nombre', 'apellido', 'email', 'telefono', 'cedula', 'direccion', 'salario', 'password'];
            return piiKeywords.some(k => colName.toLowerCase().includes(k));
        };

        return schema.map(item => ({
            ...item,
            column_name: isPii(item.column_name) ? `ANON_${item.column_name}` : item.column_name
        }));
    }
}

module.exports = new DatabaseService();
